interface MockElement {
  type: 'rect' | 'circle' | 'sticky' | 'text';
  left: number; // 0-1 relative to canvas width
  top: number; // 0-1 relative to canvas height
  width?: number; // 0-1 relative to canvas width
  height?: number; // 0-1 relative to canvas height
  radius?: number; // 0-1 relative to min(width, height)
  fill: string;
  stroke?: string;
  text?: string;
  fontSize?: number;
  fontColor?: string;
}

export const MOCK_BOARD_CONTENT: Record<string, MockElement[]> = {
  '1': [
    {
      type: 'sticky',
      left: 0.04,
      top: 0.06,
      width: 0.18,
      height: 0.16,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'User auth flow',
      fontSize: 14,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 0.27,
      top: 0.06,
      width: 0.18,
      height: 0.16,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Payment integration',
      fontSize: 14,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 0.5,
      top: 0.06,
      width: 0.18,
      height: 0.16,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'Dashboard MVP ✅',
      fontSize: 14,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 0.04,
      top: 0.33,
      width: 0.28,
      height: 0.22,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: 'Sprint Goal:\nShip checkout',
      fontSize: 14,
      fontColor: '#1E3A5F',
    },
    {
      type: 'rect',
      left: 0.38,
      top: 0.33,
      width: 0.28,
      height: 0.22,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Blocked:\nWaiting on API',
      fontSize: 14,
      fontColor: '#991B1B',
    },
    {
      type: 'text',
      left: 0.72,
      top: 0.14,
      width: 0.2,
      height: 0.05,
      fill: 'transparent',
      text: '← Drag to prioritize',
      fontSize: 15,
      fontColor: '#9CA3AF',
    },
  ],
  '2': [
    {
      type: 'circle',
      left: 0.35,
      top: 0.08,
      radius: 0.1,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: 'Core Idea',
      fontSize: 15,
      fontColor: '#1E3A5F',
    },
    {
      type: 'sticky',
      left: 0.04,
      top: 0.05,
      width: 0.18,
      height: 0.15,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'AI suggestions',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 0.62,
      top: 0.05,
      width: 0.18,
      height: 0.15,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Realtime collab',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 0.04,
      top: 0.48,
      width: 0.18,
      height: 0.15,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Templates',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'sticky',
      left: 0.62,
      top: 0.48,
      width: 0.18,
      height: 0.15,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Export to Figma',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'text',
      left: 0.25,
      top: 0.72,
      width: 0.4,
      height: 0.05,
      fill: 'transparent',
      text: '🧠 Product Brainstorm',
      fontSize: 17,
      fontColor: '#374151',
    },
  ],
  '3': [
    {
      type: 'rect',
      left: 0.03,
      top: 0.05,
      width: 0.28,
      height: 0.1,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'Went well ✅',
      fontSize: 14,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 0.35,
      top: 0.05,
      width: 0.28,
      height: 0.1,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'To improve 🔧',
      fontSize: 14,
      fontColor: '#92400E',
    },
    {
      type: 'rect',
      left: 0.67,
      top: 0.05,
      width: 0.28,
      height: 0.1,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Actions 🎯',
      fontSize: 14,
      fontColor: '#991B1B',
    },
    {
      type: 'sticky',
      left: 0.03,
      top: 0.22,
      width: 0.28,
      height: 0.13,
      fill: '#BBF7D0',
      text: 'Shipped on time',
      fontSize: 13,
      fontColor: '#166534',
    },
    {
      type: 'sticky',
      left: 0.03,
      top: 0.4,
      width: 0.28,
      height: 0.13,
      fill: '#BBF7D0',
      text: 'Good morale',
      fontSize: 13,
      fontColor: '#166534',
    },
    {
      type: 'sticky',
      left: 0.35,
      top: 0.22,
      width: 0.28,
      height: 0.13,
      fill: '#FDE68A',
      text: 'Too many meetings',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 0.67,
      top: 0.22,
      width: 0.28,
      height: 0.13,
      fill: '#FECACA',
      text: 'Reduce standup',
      fontSize: 13,
      fontColor: '#991B1B',
    },
  ],
  '4': [
    {
      type: 'rect',
      left: 0.33,
      top: 0.05,
      width: 0.22,
      height: 0.1,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: 'API Gateway',
      fontSize: 14,
      fontColor: '#1E3A5F',
    },
    {
      type: 'rect',
      left: 0.05,
      top: 0.28,
      width: 0.2,
      height: 0.1,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Auth Service',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'rect',
      left: 0.34,
      top: 0.28,
      width: 0.2,
      height: 0.1,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Board Service',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'rect',
      left: 0.63,
      top: 0.28,
      width: 0.2,
      height: 0.1,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'AI Service',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'rect',
      left: 0.1,
      top: 0.52,
      width: 0.18,
      height: 0.1,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'PostgreSQL',
      fontSize: 13,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 0.36,
      top: 0.52,
      width: 0.18,
      height: 0.1,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Redis',
      fontSize: 13,
      fontColor: '#991B1B',
    },
    {
      type: 'rect',
      left: 0.62,
      top: 0.52,
      width: 0.18,
      height: 0.1,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Kafka',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'text',
      left: 0.28,
      top: 0.72,
      width: 0.4,
      height: 0.05,
      fill: 'transparent',
      text: 'System Architecture',
      fontSize: 16,
      fontColor: '#6B7280',
    },
  ],
  '5': [
    {
      type: 'circle',
      left: 0.03,
      top: 0.08,
      radius: 0.04,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: '👤',
      fontSize: 20,
      fontColor: '#1E3A5F',
    },
    {
      type: 'rect',
      left: 0.14,
      top: 0.08,
      width: 0.15,
      height: 0.1,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Cart',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'rect',
      left: 0.34,
      top: 0.08,
      width: 0.15,
      height: 0.1,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Address',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'rect',
      left: 0.54,
      top: 0.08,
      width: 0.15,
      height: 0.1,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Payment',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'rect',
      left: 0.74,
      top: 0.08,
      width: 0.15,
      height: 0.1,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'Confirm ✅',
      fontSize: 13,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 0.34,
      top: 0.32,
      width: 0.15,
      height: 0.1,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Error',
      fontSize: 13,
      fontColor: '#991B1B',
    },
    {
      type: 'rect',
      left: 0.54,
      top: 0.32,
      width: 0.15,
      height: 0.1,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Retry',
      fontSize: 13,
      fontColor: '#5B21B6',
    },
    {
      type: 'text',
      left: 0.25,
      top: 0.55,
      width: 0.4,
      height: 0.05,
      fill: 'transparent',
      text: 'Checkout Flow',
      fontSize: 16,
      fontColor: '#374151',
    },
  ],
  '6': [
    {
      type: 'rect',
      left: 0.04,
      top: 0.05,
      width: 0.35,
      height: 0.1,
      fill: '#EFF6FF',
      stroke: '#BFDBFE',
      text: 'Design Tokens',
      fontSize: 16,
      fontColor: '#2563EB',
    },
    { type: 'circle', left: 0.05, top: 0.22, radius: 0.03, fill: '#2563EB', stroke: '#1D4ED8' },
    { type: 'circle', left: 0.12, top: 0.22, radius: 0.03, fill: '#3B82F6', stroke: '#2563EB' },
    { type: 'circle', left: 0.19, top: 0.22, radius: 0.03, fill: '#60A5FA', stroke: '#3B82F6' },
    { type: 'circle', left: 0.26, top: 0.22, radius: 0.03, fill: '#93C5FD', stroke: '#60A5FA' },
    { type: 'circle', left: 0.33, top: 0.22, radius: 0.03, fill: '#BFDBFE', stroke: '#93C5FD' },
    {
      type: 'rect',
      left: 0.04,
      top: 0.4,
      width: 0.15,
      height: 0.1,
      fill: '#2563EB',
      stroke: '#1D4ED8',
      text: 'Primary',
      fontSize: 13,
      fontColor: '#FFFFFF',
    },
    {
      type: 'rect',
      left: 0.22,
      top: 0.4,
      width: 0.15,
      height: 0.1,
      fill: '#FFFFFF',
      stroke: '#D1D5DB',
      text: 'Secondary',
      fontSize: 13,
      fontColor: '#374151',
    },
    {
      type: 'rect',
      left: 0.4,
      top: 0.4,
      width: 0.15,
      height: 0.1,
      fill: '#F3F4F6',
      stroke: '#E5E7EB',
      text: 'Ghost',
      fontSize: 13,
      fontColor: '#6B7280',
    },
    {
      type: 'text',
      left: 0.04,
      top: 0.58,
      width: 0.4,
      height: 0.05,
      fill: 'transparent',
      text: 'Aa Inter — 16 / 24 / 32',
      fontSize: 15,
      fontColor: '#9CA3AF',
    },
  ],
};

export function getMockContent(boardId: string): MockElement[] {
  return MOCK_BOARD_CONTENT[boardId] ?? MOCK_BOARD_CONTENT['1'];
}
