interface MockElement {
  type: 'rect' | 'circle' | 'sticky' | 'text';
  left: number;
  top: number;
  width?: number;
  height?: number;
  radius?: number;
  fill: string;
  stroke?: string;
  text?: string;
  fontSize?: number;
  fontColor?: string;
}

export const MOCK_BOARD_CONTENT: Record<string, MockElement[]> = {
  '1': [
    {
      type: 'sticky',
      left: 50,
      top: 50,
      width: 140,
      height: 100,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'User auth flow',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 220,
      top: 50,
      width: 140,
      height: 100,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Payment integration',
      fontSize: 13,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 390,
      top: 50,
      width: 140,
      height: 100,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'Dashboard MVP ✅',
      fontSize: 13,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 50,
      top: 200,
      width: 200,
      height: 120,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: 'Sprint Goal:\nShip checkout by Friday',
      fontSize: 14,
      fontColor: '#1E3A5F',
    },
    {
      type: 'rect',
      left: 300,
      top: 200,
      width: 200,
      height: 120,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Blocked:\nWaiting on API spec',
      fontSize: 14,
      fontColor: '#991B1B',
    },
    {
      type: 'text',
      left: 550,
      top: 80,
      width: 200,
      height: 30,
      fill: 'transparent',
      text: '← Drag to prioritize',
      fontSize: 16,
      fontColor: '#9CA3AF',
    },
  ],
  '2': [
    {
      type: 'circle',
      left: 250,
      top: 100,
      radius: 60,
      fill: '#DBEAFE',
      stroke: '#2563EB',
      text: 'Core Idea',
      fontSize: 14,
      fontColor: '#1E3A5F',
    },
    {
      type: 'sticky',
      left: 50,
      top: 40,
      width: 130,
      height: 80,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'AI-powered suggestions',
      fontSize: 11,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 420,
      top: 40,
      width: 130,
      height: 80,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'Real-time collaboration',
      fontSize: 11,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 50,
      top: 250,
      width: 130,
      height: 80,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Template marketplace',
      fontSize: 11,
      fontColor: '#5B21B6',
    },
    {
      type: 'sticky',
      left: 420,
      top: 250,
      width: 130,
      height: 80,
      fill: '#EDE9FE',
      stroke: '#8B5CF6',
      text: 'Export to Figma',
      fontSize: 11,
      fontColor: '#5B21B6',
    },
    {
      type: 'text',
      left: 200,
      top: 350,
      width: 300,
      height: 30,
      fill: 'transparent',
      text: '🧠 Product Brainstorm — Q2 2026',
      fontSize: 18,
      fontColor: '#374151',
    },
  ],
  '3': [
    {
      type: 'rect',
      left: 30,
      top: 30,
      width: 220,
      height: 40,
      fill: '#DCFCE7',
      stroke: '#22C55E',
      text: 'What went well ✅',
      fontSize: 14,
      fontColor: '#166534',
    },
    {
      type: 'rect',
      left: 280,
      top: 30,
      width: 220,
      height: 40,
      fill: '#FEF3C7',
      stroke: '#F59E0B',
      text: 'To improve 🔧',
      fontSize: 14,
      fontColor: '#92400E',
    },
    {
      type: 'rect',
      left: 530,
      top: 30,
      width: 220,
      height: 40,
      fill: '#FEE2E2',
      stroke: '#EF4444',
      text: 'Action items 🎯',
      fontSize: 14,
      fontColor: '#991B1B',
    },
    {
      type: 'sticky',
      left: 30,
      top: 90,
      width: 220,
      height: 60,
      fill: '#BBF7D0',
      text: 'Shipped on time',
      fontSize: 12,
      fontColor: '#166534',
    },
    {
      type: 'sticky',
      left: 30,
      top: 165,
      width: 220,
      height: 60,
      fill: '#BBF7D0',
      text: 'Good team morale',
      fontSize: 12,
      fontColor: '#166534',
    },
    {
      type: 'sticky',
      left: 280,
      top: 90,
      width: 220,
      height: 60,
      fill: '#FDE68A',
      text: 'Too many meetings',
      fontSize: 12,
      fontColor: '#92400E',
    },
    {
      type: 'sticky',
      left: 530,
      top: 90,
      width: 220,
      height: 60,
      fill: '#FECACA',
      text: 'Reduce standup to 10min',
      fontSize: 12,
      fontColor: '#991B1B',
    },
  ],
};

export function getMockContent(boardId: string): MockElement[] {
  return MOCK_BOARD_CONTENT[boardId] ?? MOCK_BOARD_CONTENT['1'];
}
